# Generated by Django 4.0.5 on 2022-06-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='service',
            field=models.ManyToManyField(to='backend.service'),
        ),
    ]
